# Generated by Django 5.0.4 on 2024-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="sab_activ",
            field=models.BooleanField(
                default=True, verbose_name="подписан не подписан"
            ),
        ),
    ]
