# Generated by Django 5.0.4 on 2024-07-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0004_subscription_sab_activ"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на платеж"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Session ID"
            ),
        ),
    ]
