# Generated by Django 5.0.4 on 2024-07-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0005_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="well",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
